Output libmanager.gif

Set WindowBar Colorful   
Set FontSize 20
Set Width 1000
Set Height 600
Set TypingSpeed 100ms
Set Theme "Dracula"

Type "python3 ./src/main.py" Enter Sleep 1s

# Adicionar livro
Type "1" Sleep 500ms Enter Sleep 500ms
Type "Quincas Borbas" Enter Sleep 500ms
Type "M. de Assis" Enter Sleep 500ms
Type "1891" Enter Sleep 1s
Enter Sleep 500ms

# Visualizar livros
Type "4" Sleep 500ms Enter Sleep 2s
Enter Sleep 1s

# Sair
Type "5" Enter Sleep 2s
